# Generated by Django 2.2.2 on 2019-12-13 15:20

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import mediafiles.models
import mediafiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, unique=True, verbose_name='Название блока')),
                ('urlPhotos', models.CharField(default='', max_length=201, verbose_name='Ссылка на альбомы вк')),
                ('urlVideos', models.CharField(default='', max_length=201, verbose_name='Ссылка на ютуб-канал')),
            ],
            options={
                'verbose_name_plural': 'Медиа',
                'verbose_name': 'Медиа',
            },
        ),
        migrations.CreateModel(
            name='MediaVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=201, verbose_name='Ссылка')),
                ('title', models.CharField(default='', max_length=201, verbose_name='Название')),
                ('customOrder', models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место')),
                ('id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediafiles.MediaFiles')),
            ],
            options={
                'ordering': ['customOrder'],
                'verbose_name_plural': 'Видео',
                'verbose_name': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='MediaPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=201, verbose_name='Ссылка')),
                ('imageOld', models.ImageField(blank=True, default='', upload_to=mediafiles.models.MediaPhotos.user_directory_path, validators=[mediafiles.validators.validate_image], verbose_name='Картинка')),
                ('image', image_cropping.fields.ImageRatioField('imageOld', '280x140', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Выберите область для отображения картинки', hide_image_field=False, size_warning=True, verbose_name='Отображение картинки')),
                ('customOrder', models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место')),
                ('title', models.CharField(default='', max_length=201, verbose_name='Название')),
                ('id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediafiles.MediaFiles')),
            ],
            options={
                'ordering': ['customOrder'],
                'verbose_name_plural': 'Фотоальбомы',
                'verbose_name': 'Фотоальбом',
            },
        ),
    ]
