# Generated by Django 2.2.2 on 2019-12-13 15:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import image_cropping.fields
import news.models
import news.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=400, verbose_name='Заголовок Новости')),
                ('titlePreview', models.TextField(blank=True, default='', max_length=500, verbose_name='Превью Новости')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и Время')),
                ('imageOld', models.ImageField(default='', upload_to=news.models.News.user_directory_path, validators=[news.validators.validate_image], verbose_name='Картинка к новости')),
                ('image', image_cropping.fields.ImageRatioField('imageOld', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Выберите область для отображения картинки в маленьком варианте', hide_image_field=False, size_warning=True, verbose_name='Маленькая картинка')),
                ('imageBig', image_cropping.fields.ImageRatioField('imageOld', '900x315', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Выберите область для отображения картинки в большом варианте', hide_image_field=False, size_warning=True, verbose_name='Большая картинка')),
                ('main', models.BooleanField(default=False, verbose_name='Главная новость')),
                ('important', models.BooleanField(default=False, verbose_name='Важная новость')),
                ('trends', models.ManyToManyField(blank=True, to='trends.Trends', verbose_name='Выберите Направления')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name_plural': 'Новости',
                'verbose_name': 'Новость',
            },
        ),
        migrations.CreateModel(
            name='NewsBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topLine', models.BooleanField(default=False, verbose_name='Верхняя линия')),
                ('title', models.CharField(blank=True, default='', max_length=101, verbose_name='Подзаголовок')),
                ('text', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Текст')),
                ('bottomLine', models.BooleanField(default=False, verbose_name='Нижняя линия')),
                ('customOrder', models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место')),
                ('include', models.BooleanField(verbose_name='Блок включен в новость')),
                ('id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
            options={
                'ordering': ['customOrder'],
                'verbose_name_plural': 'Блоки новости',
                'verbose_name': 'Блок новости',
            },
        ),
        migrations.CreateModel(
            name='NewsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='', upload_to='news/', validators=[news.validators.validate_file_extension], verbose_name='Картинка или видео')),
                ('ext', models.CharField(blank=True, max_length=5)),
                ('label', models.CharField(blank=True, max_length=150, verbose_name='Подпись к файлу')),
                ('id_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.NewsBlock')),
            ],
            options={
                'verbose_name_plural': 'Файл',
                'verbose_name': 'Файл',
            },
        ),
        migrations.AddIndex(
            model_name='newsblock',
            index=models.Index(fields=['title'], name='news_newsbl_title_55a70c_idx'),
        ),
        migrations.AddIndex(
            model_name='newsblock',
            index=models.Index(fields=['text'], name='news_newsbl_text_32244b_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['titlePreview'], name='news_news_titlePr_0c68c5_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['title'], name='news_news_title_ef31ad_idx'),
        ),
    ]
