# Generated by Django 2.2.2 on 2019-12-13 15:20

import ckeditor.fields
import districts.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=801, verbose_name='Название отдела/сектора')),
                ('customOrder', models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место')),
            ],
            options={
                'ordering': ['customOrder'],
                'verbose_name_plural': 'Отдел/Сектор',
                'verbose_name': 'Отдел/Сектор',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=201, verbose_name='Название территории')),
                ('image', models.ImageField(default='', upload_to='districts/', validators=[districts.validators.validate_image], verbose_name='Карта территории')),
                ('isCity', models.BooleanField(default=False, verbose_name='Город')),
                ('isMainCity', models.BooleanField(default=False, verbose_name='Главный город территорий')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, default='', max_length=101, verbose_name='Почта')),
                ('address', models.CharField(blank=True, default='', max_length=301, verbose_name='Адрес')),
                ('map', models.CharField(blank=True, default='', max_length=1501, verbose_name='Ссылка на яндекс-карту')),
                ('url', models.CharField(blank=True, default='', max_length=201, verbose_name='Ссылка на сайт')),
                ('vk', models.CharField(blank=True, default='', max_length=101, verbose_name='Вконтакте')),
                ('instagram', models.CharField(blank=True, default='', max_length=101, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, default='', max_length=101, verbose_name='Facebook')),
                ('countYouth', models.CharField(blank=True, default='', max_length=100, verbose_name='Молодых пользователей')),
                ('percentageYouth', models.CharField(blank=True, default='', max_length=100, verbose_name='Процент молодежи от числа жителей региона')),
            ],
            options={
                'ordering': ['-isMainCity', '-isCity', 'title'],
                'verbose_name_plural': 'Территории',
                'verbose_name': 'Территория',
            },
        ),
        migrations.CreateModel(
            name='DistrictMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Территории(Главная Страница)',
                'verbose_name': 'Территория(Главная Страница)',
            },
        ),
        migrations.CreateModel(
            name='DistrictContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=301, verbose_name='Имя')),
                ('position', models.CharField(blank=True, default='', max_length=501, verbose_name='Должность')),
                ('image', models.ImageField(blank=True, default='', upload_to='districts/', validators=[districts.validators.validate_image], verbose_name='Фото')),
                ('phone', models.CharField(blank=True, default='', max_length=300, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, default='', max_length=301, verbose_name='Почта')),
                ('customOrder', models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='districts.Department', verbose_name='Отдел/сектор')),
                ('id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='districts.District')),
            ],
            options={
                'ordering': ['customOrder'],
                'verbose_name_plural': 'Контакты',
                'verbose_name': 'Контакт',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='districts.DistrictMain'),
        ),
        migrations.AddField(
            model_name='department',
            name='id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='districts.District'),
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=201, verbose_name='Название органа')),
                ('text', ckeditor.fields.RichTextField(blank=True, default='', max_length=201, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default='', upload_to='districts/', validators=[districts.validators.validate_image], verbose_name='Картинка')),
                ('customOrder', models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место')),
                ('id_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='districts.District')),
            ],
            options={
                'ordering': ['customOrder'],
                'verbose_name_plural': 'Органы',
                'verbose_name': 'Орган',
            },
        ),
        migrations.AddIndex(
            model_name='districtcontacts',
            index=models.Index(fields=['name'], name='districts_d_name_6c9d36_idx'),
        ),
        migrations.AddIndex(
            model_name='districtcontacts',
            index=models.Index(fields=['position'], name='districts_d_positio_459bea_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['title'], name='districts_d_title_f2b25e_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['title'], name='districts_d_title_5b5c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['title'], name='districts_a_title_aeae6f_idx'),
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['text'], name='districts_a_text_e12a3f_idx'),
        ),
    ]
