# Generated by Django 2.2.2 on 2019-12-13 15:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import trends.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, unique=True, verbose_name='Название направления')),
                ('text', ckeditor.fields.RichTextField(default='', verbose_name='Текст')),
                ('imageInactive', models.ImageField(blank=True, default='', upload_to='trends/', validators=[trends.validators.validate_image], verbose_name='Картинка неактивная')),
                ('imageActive', models.ImageField(blank=True, default='', upload_to='trends/', validators=[trends.validators.validate_image], verbose_name='Картинка при наведении')),
                ('customOrder', models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место')),
            ],
            options={
                'ordering': ['customOrder'],
                'verbose_name_plural': 'Направления',
                'verbose_name': 'Направление',
            },
        ),
        migrations.CreateModel(
            name='TrendsPartners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Партнер')),
                ('image', models.ImageField(blank=True, default='', upload_to='trends/', validators=[trends.validators.validate_image], verbose_name='Картинка')),
                ('url', models.CharField(blank=True, default='', max_length=1001, verbose_name='Ссылка на сайт')),
                ('customOrder', models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место')),
                ('id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.Trends')),
            ],
            options={
                'ordering': ['customOrder'],
                'verbose_name_plural': 'Партнеры',
                'verbose_name': 'Партнер',
            },
        ),
        migrations.CreateModel(
            name='TrendsHrefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1500, verbose_name='Название')),
                ('url', models.CharField(default='', max_length=1500, verbose_name='Ссылка')),
                ('customOrder', models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место')),
                ('id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.Trends')),
            ],
            options={
                'ordering': ['customOrder'],
                'verbose_name_plural': 'Иные ссылки',
                'verbose_name': 'Иная ссылка',
            },
        ),
        migrations.CreateModel(
            name='TrendsDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Заголовок')),
                ('file', models.FileField(blank=True, default='', upload_to='trends/', validators=[trends.validators.validate_documents], verbose_name='Файл')),
                ('customOrder', models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место')),
                ('id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.Trends')),
            ],
            options={
                'ordering': ['customOrder'],
                'verbose_name_plural': 'Документы',
                'verbose_name': 'Документ',
            },
        ),
        migrations.CreateModel(
            name='TrendsContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Имя')),
                ('position', models.CharField(blank=True, default='', max_length=201, verbose_name='Должность')),
                ('image', models.ImageField(blank=True, default='', upload_to='trends/', validators=[trends.validators.validate_image], verbose_name='Картинка')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, default='', max_length=101, verbose_name='Почта')),
                ('customOrder', models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место')),
                ('id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.Trends')),
            ],
            options={
                'ordering': ['customOrder'],
                'verbose_name_plural': 'Контакты',
                'verbose_name': 'Контакт',
            },
        ),
        migrations.AddIndex(
            model_name='trends',
            index=models.Index(fields=['title'], name='trends_tren_title_27e885_idx'),
        ),
        migrations.AddIndex(
            model_name='trends',
            index=models.Index(fields=['text'], name='trends_tren_text_be6e19_idx'),
        ),
        migrations.AddIndex(
            model_name='trendscontacts',
            index=models.Index(fields=['name'], name='trends_tren_name_1f4a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='trendscontacts',
            index=models.Index(fields=['position'], name='trends_tren_positio_682dd7_idx'),
        ),
    ]
