# Generated by Django 2.2.2 on 2019-12-13 15:20

from django.db import migrations, models
import django.utils.timezone
import flagmans.models
import flagmans.validators
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flagmans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='Название флагмана')),
                ('imageOld', models.ImageField(blank=True, default='', upload_to=flagmans.models.Flagmans.user_directory_path, validators=[flagmans.validators.validate_image], verbose_name='Картинка')),
                ('image', image_cropping.fields.ImageRatioField('imageOld', '320x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Выберите область для отображения картинки', hide_image_field=False, size_warning=True, verbose_name='Отображение картинки')),
                ('address', models.CharField(blank=True, default='', max_length=301, verbose_name='Место проведения')),
                ('url', models.CharField(blank=True, default='', max_length=201, verbose_name='Ссылка')),
                ('map', models.CharField(blank=True, default='', max_length=1501, verbose_name='Ссылка на яндекс-карту')),
                ('dateEnd', models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания/проведения')),
                ('dateStart', models.DateField(blank=True, null=True, verbose_name='Дата начала(ОСТАВЬТЕ ПУСТЫМ, ЕСЛИ У ФЛАГМАНА НЕТ ПЕРИОДА ПРОВЕДЕНИЯ)')),
                ('date', models.CharField(default='', max_length=100, verbose_name='Строковое представление даты')),
            ],
            options={
                'ordering': ['dateStart', '-dateEnd'],
                'verbose_name_plural': 'Флагманы',
                'verbose_name': 'Флагман',
            },
        ),
        migrations.AddIndex(
            model_name='flagmans',
            index=models.Index(fields=['title'], name='flagmans_fl_title_8df3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='flagmans',
            index=models.Index(fields=['address'], name='flagmans_fl_address_e70a78_idx'),
        ),
    ]
