# Generated by Django 2.2.2 on 2019-12-13 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flagmans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagmans',
            name='dateEnd',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала(ОСТАВЬТЕ ПУСТЫМ, ЕСЛИ У ФЛАГМАНА НЕТ ПЕРИОДА ПРОВЕДЕНИЯ)'),
        ),
        migrations.AlterField(
            model_name='flagmans',
            name='dateStart',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания/проведения'),
        ),
    ]
