# Generated by Django 2.2.2 on 2020-01-31 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunities',
            options={'ordering': ['dateStart', 'dateEnd'], 'verbose_name': 'Возможность', 'verbose_name_plural': 'Возможности'},
        ),
        migrations.AddField(
            model_name='opportunities',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Отображение на главной странице'),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='dateEnd',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания/проведения(ОСТАВЬТЕ ПУСТЫМ, ЕСЛИ У ВОЗМОЖНОСТИ НЕТ ПЕРИОДА ПРОВЕДЕНИЯ)'),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='dateStart',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата начала'),
        ),
    ]
