# Generated by Django 2.2.2 on 2019-12-13 15:20

import about.validators
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time', ckeditor.fields.RichTextField(default='', verbose_name='Режим работы')),
                ('text', ckeditor.fields.RichTextField(default='', verbose_name='Информация')),
                ('email', models.CharField(default='', max_length=100, verbose_name='Электронная почта')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, default='', max_length=301, verbose_name='Адрес')),
                ('map', models.CharField(blank=True, default='', max_length=1501, verbose_name='Ссылка на Яндекс-карту')),
            ],
            options={
                'verbose_name_plural': 'О нас',
                'verbose_name': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='AboutBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Название отдела')),
                ('customOrder', models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место')),
                ('id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.About')),
            ],
            options={
                'ordering': ['customOrder'],
                'verbose_name_plural': 'Отделы',
                'verbose_name': 'Отдел',
            },
        ),
        migrations.CreateModel(
            name='AboutBlockPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='ФИО')),
                ('image', models.ImageField(default='', upload_to='about/', validators=[about.validators.validate_image], verbose_name='Картинка')),
                ('position', models.CharField(default='', max_length=100, verbose_name='Должность')),
                ('email', models.CharField(default='', max_length=100, verbose_name='Электронная почта')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Номер телефона')),
                ('customOrder', models.PositiveIntegerField(default=0, verbose_name='Перетащите на нужное место')),
                ('id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.AboutBlock')),
            ],
            options={
                'ordering': ['customOrder'],
                'verbose_name_plural': 'Работники',
                'verbose_name': 'Работник',
            },
        ),
    ]
